% This script computes and records the relative residual 
% and orthogonality loss for different randomized  
% orthogonalization schemes and step sizes s in RBGS-GMRES 

% The result is recorded in relResAll{} and orthLossAll

%rng(0);
% load the matrix
% matrix from SuiteSparse
%matnum = 'SiH4';
%S = load([matnum '.mat']);
%matrix = S.Problem.A;
%n = size(matrix, 1);
% convert to function handle
%A = @(x) matrix * x;

% matrix generated by function 'getStartMatrix'
n = 5000;
alpha = 0;
matrix = getStartMatrix(n, alpha);
matnum = 'genMatrix(1e3)';
A = matrix;

% step size
ss = 5:5:40;
l = length(ss);

ctol = 1e-16;
runs = 5;

% AOB_options for RBGS
AOB_options = ["rCGS2", "rCGS", "RGS", "rMGS"];
%AOB_options = ["rMGS"];
% WB_options for RBGS
WB_options = ["rCGS", "rCGS2", "RGS", "rMGS", "rCholesky"];
%WB_options = ["rCGS"];

relResAll   = cell(length(WB_options),length(AOB_options), l);
orthLossAll = cell(length(WB_options),length(AOB_options), l);
for vs = 1:l
    s = ss(vs);
    p = round(500/s);
    m = p * s + 1;
    d = 2 * m;
    % Newton Basis
    RitzValues = getRitzValues(A, ritz, s);
    basisFunc = @(Afun, q, s) mpk(Afun, q, s, RitzValues);
    % Monomial Basis    
    %basisFunc = @mpk;
    for aob = 1:length(AOB_options)
        for wb = 1:length(WB_options)
            % orthogonalized methods for RBGS
            orth_option = [aob, wb];
            AOB = AOB_options(orth_option(1));
            WB = WB_options(orth_option(2));
            fprintf('Starting AOB = %s, WB = %s, s = %d \n', AOB, WB, s);
            
            % record the result for RBGS
            iters_RBGS = [];   % record the iteration number 
            relRes0 = {};   % record the relative residual in each run
                           % length(beta_eachRun) * runs
            orthLoss0 = {};  % record the orthogonality loss in each run
                           % length(orthLoss_eachRun) * runs        
            iters = zeros(runs, 1);      
            for w = 1:runs
                Theta = sparsesign(d, n, 8);
                %Theta = Gaussian(d, n);
                [~, beta, orth] = RBGS_GMRES(A, s, p, Theta, basisFunc, ...
                    AOB, WB, b, ctol);
                iters(w) = length(beta) - 1;             
                relRes0{end+1} = beta;
                orthLoss0{end+1} = orth;                
            end    
            %collect results
            iters_RBGS = [iters_RBGS; iters];
            
            % compute the statistics for RBGS for plot        
            % mean for relRes
            % convert relRes to a matrix, pad the shorter vector with NaNs
            maxLen = max(cellfun(@length, relRes0));
            relRes_RBGS = nan(runs, maxLen);
            for k = 1:runs
                relRes_RBGS(k,1:numel(relRes0{k})) = relRes0{k};
            end
            relRes_mean = nanmean(relRes_RBGS,1); % 1-by-maxLen
            relResAll{wb, aob, vs}   = relRes_mean;
            
            % mean for orth
            maxLen_orth = max(cellfun(@length, orthLoss0));
            orthLoss_RBGS = nan(runs, maxLen_orth);    
            for k = 1:runs
                orthLoss_RBGS(k, 1:numel(orthLoss0{k})) = orthLoss0{k};
            end
            orthLoss_mean = nanmean(orthLoss_RBGS, 1);
            orthLossAll{wb, aob, vs} = orthLoss_mean;
        end
    end
end
